<?php
	include("config.php");

	if($_SERVER["REQUEST_METHOD"] == "POST") {
		// username and password sent from form 

		$myusername = mysqli_real_escape_string($db,$_POST['username']);
		$mypassword = mysqli_real_escape_string($db,$_POST['password']); 

		$sql = "SELECT id,active FROM admin WHERE username = '$myusername' and passcode = '$mypassword'";
		$result = mysqli_query($db,$sql);
		$row = mysqli_fetch_array($result,MYSQLI_ASSOC);
		//print_r($row);
		$active = $row['active'];

		$count = mysqli_num_rows($result);

		// If result matched $myusername and $mypassword, table row must be 1 row

		if($count == 1) {
			session_start();
			//session_register("myusername");
			$_SESSION['login_user'] = $myusername;

			header("location: welcome.phtml");
		}else {
			$error = "Your Login Name or Password is invalid";
		}
	}
?>
<html>
	<head>
		<link rel="stylesheet" type="text/css" href="css/bootstrap.css">
		<link rel="stylesheet" type="text/css" href="css/theme.css">
	</head>
	<body>
		<?php include ("header.php"); ?>
		<section id="login">
			<div class="container">
				<div class="row">
					<div class="col-xs-12">
						<div class="form-wrap">
						<h1>Log in with your email account</h1>
							<form role="form" action="<?php echo 'login.phtml'; ?>" method="post" id="login-form" autocomplete="off">
								<div class="form-group">
									<label for="email" class="sr-only">Username</label>
									<input type="text" name="username" id="email" class="form-control" placeholder="Username">
								</div>
								<div class="form-group">
									<label for="key" class="sr-only">Password</label>
									<input type="password" name="password" id="key" class="form-control" placeholder="Password">
								</div>
								<div class="checkbox">
									<span class="character-checkbox" onclick="showPassword()"></span>
									<span class="label">Show password</span>
								</div>
								<input type="submit" id="btn-login" class="btn btn-custom btn-lg btn-block" value="Log in">
							</form>
							<!--a href="javascript:;" class="forget" data-toggle="modal" data-target=".forget-modal">Forgot your password?</a-->
							<hr>
						</div>
					</div> <!-- /.col-xs-12 -->
				</div> <!-- /.row -->
			</div> <!-- /.container -->
		</section>

		<div class="modal fade forget-modal" tabindex="-1" role="dialog" aria-labelledby="myForgetModalLabel" aria-hidden="true">
			<div class="modal-dialog modal-sm">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal">
							<span aria-hidden="true">×</span>
							<span class="sr-only">Close</span>
						</button>
						<h4 class="modal-title">Recovery password</h4>
					</div>
					<div class="modal-body">
						<p>Type your email account</p>
						<input type="email" name="recovery-email" id="recovery-email" class="form-control" autocomplete="off">
					</div>
					<div class="modal-footer">
						<button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
						<button type="button" class="btn btn-custom">Recovery</button>
					</div>
				</div> <!-- /.modal-content -->
			</div> <!-- /.modal-dialog -->
		</div> <!-- /.modal -->

		<footer id="footer">
			<div class="container">
				<div class="row">
					<div class="col-xs-12">
						<p>Page © - 2017</p>
						<p>Powered by <strong><a href="http://www.facebook.com/rajeshbabu.vasudevan" target="_blank">Rajesh</a></strong></p>
					</div>
				</div>
			</div>
		</footer>
		
		<!-- add js -->
		<script src="js/jquery-3.2.1.min.js"></script>
		<script src="js/theme.js"></script>
	</body>
</html>