<?php 

include('session.php');

$title = "Print View";

$sale = $_GET['sale'];
$sql = "SELECT * FROM bill_sale_order WHERE id=$sale";
$order_result = mysqli_query($db,$sql);
$order_detail = mysqli_fetch_array($order_result,MYSQLI_ASSOC);
//echo $order_detail['customer_name'];
//print_r($order_detail);exit;
$order_count = mysqli_num_rows($order_result);


$sql = "SELECT * FROM bill_sale_product_order WHERE sale_id=$sale";
$product_result = mysqli_query($db,$sql);
$product_count = mysqli_num_rows($product_result);

if(!$order_detail['vat_percent']){
	$order_detail['vat_percent'] = 14.5;
}
?>
<html>
	<?php include "head.php"; ?>
	<body style="height: initial;">
		<?php if($order_count && $product_count): ?>
			<div class="print-content" style="margin: 10px;">
				<div id="container" class="print-view">
				
					<div class="col-wid-30 dis-inline" style="border-right:1px solid black;">
						<div class="col-wid-100">
							<div class="box-content text-center">
								<div class="shop_title">
									<h4 class="">TAX INVOICE</h4>
									<h6 class="">Cash/Credit</h6>
									<img src="image/img.jpg" width="85%" title="Sri Sai Wheel Care"/>
									<hr style="margin: 5px 0px;" />
									<div>
										<span style="line-height: 11px;display: inline-block;" class="">Sales</span>
										<span style="line-height: 11px;display: inline-block;" class="left-line">Services</span>
									</div>
								</div>
								<div class="address_details">
									<h5 style="background-color: black;color: white;font-weight: bold;" class="print-title-office">OFFICE</h5>
									<h4>Sri Sai Wheel Care</h4>
									<p>No 13, 3rd mile, <br/>Thirutani Road, <br/>Polur, Arakkonam, <br/>Tamil Nadu 631003<br/> <b>Tel:</b>+91-952181410,9876543210 <br/><b>Mail : </b>srisaiwheelcare@gmail.com <br/><b>Web : </b>www.srisaiwheelcare.com</p>
									
								</div>
							</div>
						</div>
					</div>
					<div class="col-wid-70 dis-inline">
						<div class="col-wid-100">
							<div class="col-wid-50">
								<div class="col-wid-100">
									<div class="box-content text-left">
										<h3>SOLD TO:</h3>
										<div class="customer_address">
											<div style="font-size: 13px;">
												<?php echo $order_detail['customer_name']; ?><br/>
												<?php echo $order_detail['address']; ?><br/>
												<?php echo $order_detail['city']; ?>
											</div>									
										</div>
									</div>
								</div>
							</div>
							<div class="col-wid-50">
								<div class="col-wid-100">
									<div class="box-content text-left" style="width: inherit;">
										<table class="table table-bordered table-invoice-details" style="width: 100%;margin-bottom: -1px;">
											<tr>
												<td>INVOICE NO: </td>
												<td><?php echo 'SAO'.$order_detail['id']; ?></td>
												<td>DATE: </td>
												<td><?php echo date_format(new DateTime($order_detail['date_added']),"d-m-Y"); ?></td>
											</tr>
											<tr>
												<td>REFERENCE: </td>
												<td></td>
												<td>VH.NO: </td>
												<td></td>
											</tr>
											<tr>
												<td colspan=1>WAREHOUSE:</td>
												<td colspan=3></td>
											</tr>
											<tr>
												<td colspan=1>PHONE NO:</td>
												<td colspan=3></td>
											</tr>
										</table>
									</div>
								</div>
							</div>
						</div>
						<div class="col-wid-100">
							<table class="table table-bordered table-print-view" style="width: 100%;margin-bottom: 10px;">
								<thead>
									<td class="text-center" style="width: 6%;">S.NO.</td>
									<td class="text-center" style="width: 43%;">DESCRIPTION</td>
									<td class="text-center" style="width: 5%;">QTY</td>
									<td class="text-center" style="width: 22%;">UNIT PRICE</td>
									<td>AMOUNT</td>
								</thead>
								<?php $addition_line = 0; ?>
								<?php $i=1; ?>
								<?php while($product_detail = mysqli_fetch_assoc($product_result)): ?>
									<tr>
										<td><?php echo $i; ?></td>
										<td>
											<?php echo $product_detail['product_name']; ?>
											<?php 
												if(strlen($product_detail['product_name'])>32){
													$temp = $product_detail['product_name'])%30;
													$addition_line += $temp;
												}
											?>
										</td>
										<td class="text-center"><?php echo $product_detail['qty']; ?></td>
										<td class="text-right"><?php echo $product_detail['price']; ?></td>
										<td class="text-right"><?php echo number_format((float)$product_detail['total'], 2, '.', ''); ?></td>
									</tr>
								<?php $i++; ?>
								<?php endwhile; ?>
								<tr>
									<td colspan=2 class="text-right">Sub-total</td>
									<td colspan=2></td>
									<td class="text-right"><?php echo $sub_total = number_format((float)$order_detail['sub_total'], 2, '.', ''); ?></td>
								</tr>
								<tr>
									<td colspan=2 class="text-right">VAT <?php echo $order_detail['vat_percent'].'%';?></td>
									<td colspan=2></td>
									<td class="text-right"><?php echo $vat_amount = number_format((float)$order_detail['vat_amount'], 2, '.', ''); ?></td>
								</tr>
								<?php 
									$round_off = round($order_detail['grand_total'])-($sub_total+$vat_amount);
									if($round_off != 0):
								?>
									<tr>
										<td colspan=2 class="text-right">Round Off</td>
										<td colspan=2></td>
										<td class="text-right">
											<?php 
												$round_off = round($order_detail['grand_total'])-($sub_total+$vat_amount);
												$sign = '+';
												if($round_off <= 0){
													$sign = '-';
													$round_off = abs($round_off);
												}
												echo "(".$sign.")".number_format((float)$round_off, 2, '.', '');
											?>
											
										</td>
									</tr>
								<?php endif; ?>
								<tfoot>
									<td style="border-right: 0;" colspan='3'></td>
									<td style="border-left: 0;" class="text-right">Total</td>
									<td class="text-right"><?php echo number_format((float)round($order_detail['grand_total']), 2, '.', ''); ?></td>
								</tfoot>
							</table>
						</div>
						<div class="col-wid-100" style="height: 50px;">
							<div style="width: inherit;">
								<span style="padding-left: 6px;" class="">RECEIVER'S SIGNATURE</span>
								<span style="float: right;padding-right: 6px;" class="">For Sri Sai Wheel Care</span>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="control-group" style="margin: 10px;height: initial;">
				<div class="text-right">
					<button class="btn btn-primary" type="button" onclick="myPrintFunction()"><i class="fa fa-print"></i> Print</button>
					<a href="manage-sales.phtml">
						<button class="btn btn-default" type="button"><i class="fa fa-reply"></i> Back</button>
					</a>
			</div>
		<?php else: ?>
			<p class="text-center"> Sorry Order details has been found! </p>
		<?php endif; ?>
		<!-- add js -->
		<script src="js/jquery-3.2.1.min.js"></script>
		<script src="js/theme.js"></script>
	</body>
</html>
	
